name: Unit Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pest-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: json, sodium, curl

      - name: composer install
        run: composer install --prefer-dist --no-interaction

      - name: Pest (Unit-Suite)
        run: vendor/bin/pest --testsuite=Unit
